# Implement env variable later

# output: main.o sudoku.o
# 	gcc main.o sudoku.o -o main

# main.o: main.c
# 	gcc -c main.c

# sudoku.o: sudoku.c sudoku.h
# 	gcc -c sudoku.c

# clean:
# 	rm *.o main

# ------------------------------------------------
output: main.c sudoku.c
	gcc -g main.c sudoku.c -o main